### ISSUE TITLE
[BUG] service name "changedetection.io" in readme docker compose example causes errors

### ISSUE THREAD

**Issue by nopoz** [linuxserver/docker-changedetection.io#21]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The readme uses `changedetection.io` as the service name in the docker compose example. This causes a DNS resolution problem with the container's built-in example check for `https://changedetection.io/CHANGELOG.txt`. The container will resolve the hostname `changedetection.io` to the IP of the container rather than the desired external IP:

Using the current docker compose example:

```
---
services:
  changedetection.io:
    image: lscr.io/linuxserver/changedetection.io:latest
    container_name: changedetection
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - BASE_URL= #optional
      - PLAYWRIGHT_DRIVER_URL= #optional
    volumes:
      - /path/to/changedetection/config:/config
    ports:
      - 5000:5000
    restart: unless-stopped
```

Checking the name resolution with ping inside the container you get the incorrect IP of the container itself:
```
# docker exec -t -i changedetection /bin/bash
root@changedetection:/# ping changedetection.io
PING changedetection.io (172.20.0.3): 56 data bytes
64 bytes from 172.20.0.3: seq=0 ttl=64 time=0.042 ms
64 bytes from 172.20.0.3: seq=1 ttl=64 time=0.041 ms
64 bytes from 172.20.0.3: seq=2 ttl=64 time=0.039 ms
```

This could lead user to think there is something wrong within the container or it's settings, when it's just a docker DNS problem. 

This can be fixed by changing the default docker compose service name from `changedetection.io` to  `changedetection`:

```
---
services:
  changedetection:
    image: lscr.io/linuxserver/changedetection.io:latest
    container_name: changedetection
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - BASE_URL= #optional
      - PLAYWRIGHT_DRIVER_URL= #optional
    volumes:
      - /path/to/changedetection/config:/config
    ports:
      - 5000:5000
    restart: unless-stopped
```

After modification and checking name resolution in the container you get the correct external IP:

```
# docker exec -t -i changedetection /bin/bash
root@c89c27bb21f8:/# ping changedetection.io
PING changedetection.io (67.223.101.61): 56 data bytes
64 bytes from 67.223.101.61: seq=0 ttl=55 time=57.553 ms
64 bytes from 67.223.101.61: seq=1 ttl=55 time=57.497 ms
```

### Steps To Reproduce

see description

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
see description
```

### Container logs

```bash
see description
```
