### ISSUE TITLE
Playwright pip package missing

### ISSUE THREAD

**Issue by Entepotenz** [linuxserver/docker-changedetection.io#3]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
using this container with playwright browserless/chrome image works.

## Current Behavior
failure with this message in the webui: "No module named 'playwright'"

## Steps to Reproduce
1. launch container with this docker-compose configuration:
```
---
version: "2.1"
services:
  changedetection:
    image: lscr.io/linuxserver/changedetection.io:latest
    container_name: changedetection
    environment:
      - PUID=1000
      - PGID=1000
      - PLAYWRIGHT_DRIVER_URL=ws://playwright-chrome:3000/?stealth=1&--disable-web-security=true
    volumes:
      - ${PWD}/config:/config
    ports:
      - 5000:5000
    restart: unless-stopped


    playwright-chrome:
        hostname: playwright-chrome
        image: browserless/chrome
        restart: unless-stopped
        environment:
            - SCREEN_WIDTH=1920
            - SCREEN_HEIGHT=1024
            - SCREEN_DEPTH=16
            - ENABLE_DEBUGGER=false
            - PREBOOT_CHROME=true
            - CONNECTION_TIMEOUT=300000
            - MAX_CONCURRENT_SESSIONS=10
            - CHROME_REFRESH_TIME=600000
            - DEFAULT_BLOCK_ADS=true
            - DEFAULT_STEALTH=true
```
2. enable "playwright" as fetch method in "request"
3. save
4. you get the error message: "No module named 'playwright'"

## Environment
**OS:** synology 7.0
**CPU architecture:** x86_64
**How docker service was installed:** synology package manager

## Comment
I guess the python playwright package is missing.
Executing this command inside the container does show empty result:
`pip3 list | grep play`

You can find more discussion here: https://github.com/dgtlmoon/changedetection.io/discussions/944
It looks like this issue already appeared in the official changedetection.io discussion.

**Comment by j0nnymoe** [comment]
playwright won't build on alpine due to musl.

**Comment by Entepotenz** [comment]
I see. Is it possible to write this into the description of this image?
Does linuxserver have a recommended way to write this?

I would like to give people a hint that this is not going to work with playwright and avoid wasting time (like in my case :D)

**Comment by thespad** [comment]
I'll add something to the readme

**Comment by Entepotenz** [comment]
@thespad 
> I'll add something to the readme

This would be really great. :-)

Is it working with selenium? If not we could add this as another useful information in the readme

> Out of interest have you tried the separate container option from https://github.com/dgtlmoon/changedetection.io/wiki/Playwright-content-fetcher#docker-compose-based ? Or does it still need the pip module in the base image?

I think I already did this approach with the docker-compose I posted in the "Steps to Reproduce" section.

**Comment by thespad** [comment]
Sorry, I completely missed that.

I don't think it works with selenium unfortunately.

**Comment by Entepotenz** [comment]
@thespad 
I tested the linuxserver image with selenium and it is working for me (cpu x86_64)

Here is the docker-compose snippet if you want to try it for yourself:
```
---
version: "2.1"
services:
  changedetection:
    image: lscr.io/linuxserver/changedetection.io:latest
    container_name: changedetection
    environment:
      - PUID=1000
      - PGID=1000
      - WEBDRIVER_URL=http://browser-chrome:4444/wd/hub
    volumes:
      - ./config:/config
    ports:
      - 5000:5000
    restart: unless-stopped

  browser-chrome:
      hostname: browser-chrome
      image: selenium/standalone-chrome-debug:3.141.59
      environment:
          - VNC_NO_PASSWORD=1
          - SCREEN_WIDTH=1920
          - SCREEN_HEIGHT=1080
          - SCREEN_DEPTH=24
      volumes:
          # Workaround to avoid the browser crashing inside a docker container
          # See https://github.com/SeleniumHQ/docker-selenium#quick-start
          - /dev/shm:/dev/shm
      restart: unless-stopped
```
